server:
  port: 8081

#spring:
#  datasource:
#    driver-class-name: h2
#    username: asdf
#    password: asdfadsfa
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#debug: true
spring:
  main:
    web-application-type: servlet

mermer.height: 175
